import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Section,
  Text,
  Hr,
} from '@react-email/components';

interface BriefingEmailProps {
  briefingDate: string;
  content: string;
}

export default function BriefingEmail({
  briefingDate = new Date().toISOString().split('T')[0],
  content = 'Your briefing content will appear here.',
}: BriefingEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>WealthDelta Daily Briefing — {briefingDate}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={header}>
            <Text style={brandText}>WealthDelta</Text>
            <Text style={dateText}>{briefingDate}</Text>
          </Section>
          <Hr style={divider} />
          <Section style={contentSection}>
            <Heading as="h1" style={heading}>
              Daily Briefing
            </Heading>
            {content.split('\n\n').map((paragraph, i) => {
              if (paragraph.startsWith('**') || paragraph.startsWith('#')) {
                const cleaned = paragraph.replace(/[*#]+/g, '').trim();
                return (
                  <Heading as="h2" key={i} style={subheading}>
                    {cleaned}
                  </Heading>
                );
              }
              return (
                <Text key={i} style={bodyText}>
                  {paragraph}
                </Text>
              );
            })}
          </Section>
          <Hr style={divider} />
          <Section style={footer}>
            <Text style={footerText}>
              Generated by WealthDelta · Confidential
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

const main = {
  backgroundColor: '#0a0a0a',
  fontFamily: "'Sora', -apple-system, BlinkMacSystemFont, sans-serif",
};

const container = {
  margin: '0 auto',
  padding: '40px 24px',
  maxWidth: '600px',
};

const header = {
  display: 'flex' as const,
  justifyContent: 'space-between' as const,
  alignItems: 'center' as const,
  marginBottom: '8px',
};

const brandText = {
  color: '#ffffff',
  fontSize: '14px',
  fontWeight: '600' as const,
  letterSpacing: '0.05em',
  margin: '0',
};

const dateText = {
  color: 'rgba(255,255,255,0.25)',
  fontSize: '12px',
  margin: '0',
};

const divider = {
  borderColor: 'rgba(255,255,255,0.06)',
  margin: '16px 0',
};

const contentSection = {
  padding: '8px 0',
};

const heading = {
  color: '#ffffff',
  fontSize: '20px',
  fontWeight: '600' as const,
  lineHeight: '1.3',
  margin: '0 0 20px 0',
};

const subheading = {
  color: 'rgba(255,255,255,0.7)',
  fontSize: '14px',
  fontWeight: '600' as const,
  lineHeight: '1.4',
  margin: '24px 0 8px 0',
  textTransform: 'uppercase' as const,
  letterSpacing: '0.05em',
};

const bodyText = {
  color: 'rgba(255,255,255,0.5)',
  fontSize: '14px',
  lineHeight: '1.7',
  margin: '0 0 12px 0',
};

const footer = {
  paddingTop: '8px',
};

const footerText = {
  color: 'rgba(255,255,255,0.15)',
  fontSize: '11px',
  margin: '0',
};
